micronaut:
  application:
    name: testcorssimplerequest
---
#micronaut:
#  server:
#    cors:
#      enabled: true
---
netty:
  default:
    allocator:
      max-order: 3
endpoints:
  stop:
    enabled: true
    sensitive: false